"""create market_events and sync_state tables

Revision ID: d74cc3917839
Revises: 
Create Date: 2026-03-13 18:39:54.271926

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'd74cc3917839'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('market_events',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('symbol', sa.String(length=20), nullable=False),
    sa.Column('event_type', sa.String(length=50), nullable=False),
    sa.Column('event_date', sa.Date(), nullable=False),
    sa.Column('title', sa.String(length=500), nullable=False),
    sa.Column('details', sa.JSON(), nullable=True),
    sa.Column('source', sa.String(length=50), nullable=False),
    sa.Column('source_event_id', sa.String(length=200), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('symbol', 'event_type', 'event_date', name='uq_event_natural_key')
    )
    op.create_index('ix_market_events_event_date', 'market_events', ['event_date'], unique=False)
    op.create_index('ix_market_events_event_type', 'market_events', ['event_type'], unique=False)
    op.create_index('ix_market_events_symbol', 'market_events', ['symbol'], unique=False)
    op.create_table('sync_state',
    sa.Column('symbol', sa.String(length=20), nullable=False),
    sa.Column('last_synced_at', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('symbol')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('sync_state')
    op.drop_index('ix_market_events_symbol', table_name='market_events')
    op.drop_index('ix_market_events_event_type', table_name='market_events')
    op.drop_index('ix_market_events_event_date', table_name='market_events')
    op.drop_table('market_events')
    # ### end Alembic commands ###
