import uuid
from datetime import UTC, date, datetime
from typing import Any

from sqlalchemy import JSON, Date, DateTime, Index, String, UniqueConstraint
from sqlalchemy.dialects.postgresql import UUID
from sqlalchemy.orm import Mapped, mapped_column

from app.database.base import Base


class MarketEvent(Base):
    __tablename__ = "market_events"

    # Primary key - generated by us, not the provider
    id: Mapped[uuid.UUID] = mapped_column(
        UUID(as_uuid=True), primary_key=True, default=uuid.uuid4
    )

    # The three fields that identify a unique real-world event
    symbol: Mapped[str] = mapped_column(String(20), nullable=False)
    event_type: Mapped[str] = mapped_column(String(50), nullable=False)
    event_date: Mapped[date] = mapped_column(Date, nullable=False)

    title: Mapped[str] = mapped_column(String(500), nullable=False)
    details: Mapped[dict[str, Any]] = mapped_column(JSON, nullable=True)

    # Where it came from
    source: Mapped[str] = mapped_column(String(50), nullable=False)
    source_event_id: Mapped[str] = mapped_column(String(200), nullable=False)

    created_at: Mapped[datetime] = mapped_column(DateTime, default=datetime.now(UTC))
    updated_at: Mapped[datetime] = mapped_column(
        DateTime, default=datetime.utcnow, onupdate=datetime.now(UTC)
    )

    # Unique constraint. This enforces our deduplication natural key
    __table_args__ = (
        UniqueConstraint(
            "symbol", "event_type", "event_date", name="uq_event_natural_key"
        ),
        # indexes for query performance
        Index("ix_market_events_symbol", "symbol"),
        Index("ix_market_events_event_type", "event_type"),
        Index("ix_market_events_event_date", "event_date"),
    )
